language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
matrix:
  exclude:
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"
  include:
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=sdist
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "2.7"
      env: TOXENV=py27
install:
  - pip install -r requirements-testing.txt
cache: pip
script:
  - tox
